# configuration for image pre-processing using OpenCV

resize_origin:
    standard_width: 699
    standard_height: 473

gradient:
    kernel_size_row: 2   # Gradient Kernel Size
    kernel_size_col: 2  # Gradient Kernel Size

threshold:
    mode: mean  # global, mean, gaussian
    block_size: 5  # Threshold (Odd number !!)
    subtract_val: 8  # Threshold

close:
    kernel_size_row: 20  # Closing Kernel Size
    kernel_size_col: 19   # Closing Kernel Size

remove_line:
    threshold: 180  # Long Line Remove Precision
    min_line_length: 100  # Long Line Remove  Minimum Line Length
    max_line_gap: 120   # Long Line Remove Maximum Line Gap

contour:
    min_width: 8  # Minimum Contour Rectangle Size
    min_height: 8  # Minimum Contour Rectangle Size
    retrieve_mode: 0    # RETR_EXTERNAL = 0. RETR_LIST = 1, RETR_CCOMP = 2, RETR_TREE = 3, RETR_FLOODFILL = 4
    approx_method: 2  # CHAIN_APPROX_NONE = 1, CHAIN_APPROX_SIMPLE = 2, CHAIN_APPROX_TC89_KCOS = 4, CHAIN_APPROX_TC89_L1 = 3


